replacements = {
    'hiv_rdt': {1: 'Positive', 2: 'Negative'},
    'malaria_rdt': {1: 'Positive', 2: 'Negative'},
    'hepb_rdt': {1: 'Positive', 2: 'Negative'},
    'hepc_rdt': {1: 'Positive', 2: 'Negative'},
    'syphilis_rdt': {1: 'Positive', 2: 'Negative'},
    'siteregion_crf': {1: 'IKORODU', 4: 'ABAKALIKI', 2: 'OWO', 3: 'IRRUA'},
    'sex_crf': {1: 'Male', 2: 'Female'},
    'sex_rdt': {1: 'Male', 2: 'Female'},
    'clinic_crf': {1: 'ISTH', 2: 'General Hospital Ikorodu', 3: 'AEFUTHA, Abakaliki', 4: 'FMC - Owo', 5: 'Other government hospital', 6: 'Other clinic', 7: 'Other hospital'},
    'unit_crf': {1: 'GOPD', 2: 'Pediatrics', 3: 'A&E', 4: 'Annex', 5: 'Other'},
    'sex_sample': {1: 'Male', 2: 'Female'},
    'lassa_pcr': {0: 'yellow', 1: 'other than yellow'},
    'appearance_urin': {0: 'Clear', 1: 'Cloudy/other than clear'},
    'leukocyte_urin': {0: 'Negative or Normal', 1: 'Trace,1+ or 30', 2: '2+ or moderate', 3: '3+ or large'},
    'nitrite_urin': {0: 'Negative or Normal', 1: 'Positive'},
    'protein_urin': {0: 'Negative or Normal', 1: 'Trace, 1+ or 30', 2: '2+ or 100', 3: '3+ or 300', 4: '4+ or 500'},
    'blood_urin': {0: 'Negative or Normal', 1: 'Trace [hemolysis]', 2: '+25 [hemolysis]', 3: '++80 [hemolysis]', 4: '+++200 [hemolysis]', 5: '+10 [non-hemolysis]', 6: '++80 [non-hemolysis]'},
    'ketones_urin': {0: 'Negative or Normal', 1: 'Trace, 1+ small', 2: '2+, moderate, 40', 3: '3+, large, 80', 4: '4+, 160'},
    'bilirubin_urin': {0: 'Negative or Normal', 1: 'Trace, 1+ small', 2: '2+, moderate, 40', 3: '3+, large'},
    'glucose_urin': {0: 'Negative or Normal', 1: 'Trace, 1+, 50 to 150', 2: '2+ or 500', 3: '3+ or 100', 4: '4+ or 2000'},
    'bloodsample': {1: 'Yes', 0: 'No'},
    'urinesample': {1: 'Yes', 0: 'No'},
    'nasosample': {1: 'Yes', 0: 'No'},
    'salivasample': {1: 'Yes', 0: 'No'},
    'oralsample': {1: 'Yes', 0: 'No'},
    'pregnancy': {1: 'Pregnant', 2: 'Not pregnant'},
    'yellowfever_pcr': {1: 'Positive', 2: 'Negative', 3: 'Pending results', 4: 'Not run'},
    'lassa_pcr': {1: 'Positive', 2: 'Negative', 3: 'Pending results', 4: 'Not run'},
    'ebola_pcr': {1: 'Positive', 2: 'Negative', 3: 'Pending results', 4: 'Not run'},
    'marburg_pcr': {1: 'Positive', 2: 'Negative', 3: 'Pending results', 4: 'Not run'},
    'westnile_pcr': {1: 'Positive', 2: 'Negative', 3: 'Pending results', 4: 'Not run'},
    'zika_pcr': {1: 'Positive', 2: 'Negative', 3: 'Pending results', 4: 'Not run'},
    'cchf_pcr': {1: 'Positive', 2: 'Negative', 3: 'Pending results', 4: 'Not run'},
    'riftvalley_pcr': {1: 'Positive', 2: 'Negative', 3: 'Pending results', 4: 'Not run'},
    'dengue_pcr': {1: 'Positive', 2: 'Negative', 3: 'Pending results', 4: 'Not run'},
    'ony_pcr': {1: 'Positive', 2: 'Negative', 3: 'Pending results', 4: 'Not run'},
    'covid_pcr': {1: 'Positive', 2: 'Negative', 3: 'Pending results', 4: 'Not run'},
    'mpox_pcr': {1: 'Positive', 2: 'Negative', 3: 'Pending results', 4: 'Not run'},
    'other1_pcr': {1: 'Positive', 2: 'Negative', 3: 'Pending results', 4: 'Not run'},
    'other2_pcr': {1: 'Positive', 2: 'Negative', 3: 'Pending results', 4: 'Not run'},
    'other3_pcr': {1: 'Positive', 2: 'Negative', 3: 'Pending results', 4: 'Not run'},
    'syphilis_rdt': {1: 'Positive', 2: 'Negative', 3: 'Pending results', 4: 'Not run'},
    'covid_rdt': {1: 'Positive', 2: 'Negative', 3: 'Pending results', 4: 'Not run'},
    'other1_rdt': {1: 'Positive', 2: 'Negative', 3: 'Pending results', 4: 'Not run'},
    'other2_rdt': {1: 'Positive', 2: 'Negative', 3: 'Pending results', 4: 'Not run'},
    'other3_rdt': {1: 'Positive', 2: 'Negative', 3: 'Pending results', 4: 'Not run'},
    'watersource': {1: 'Stream', 2: 'Dam', 3: 'Well', 4: 'Borehole', 5: ' Pipeborne water', 6: 'Water tanker', 7: 'Sachet water', 8: 'Bottle water', 9: 'Rain water'},
    'housingrisk': {1: 'Riverside', 2: 'Water-logged area', 3: 'Bushy surroundings', 4: 'Farmland settlement', 5: 'Industrial area', 6: 'Around a dumping site', 7: ' Near a bus stop or motor park', 8: 'Near a marketplace'},
    'roofingtype': {0: 'Zinc', 1: 'Aluminum', 2: 'Asbestos', 3: 'Thatched', 4: 'Other'},
    'housingtype': {1: 'Cement', 2: 'Mud', 3: 'Wood', 4: 'Other'},
    'diagnosed_history': {1: 'Yes', 2: 'No', 3: 'Not know'},
    'result_1': {1: 'Positive', 2: 'Negative', 3: 'Inconclusive'},
    'result_2': {1: 'Positive', 2: 'Negative', 3: 'Inconclusive'},
    'result_3': {1: 'Positive', 2: 'Negative', 3: 'Inconclusive'},
    'result_4': {1: 'Positive', 2: 'Negative', 3: 'Inconclusive'},
    'vomiblood_details': {1: 'Bright red', 2: 'Coffee/dark brown'},
    'stoolblood_details': {1: 'Bright red', 2: 'Coffee/dark brown'},
    'urine_details': {1: 'Dark yellow', 2: 'Red', 3: 'Browm'},
    'cough_details': {1: 'with sputum production', 2: 'bloody sputum ', 3: 'Dry'},
    'feverd': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'lethargyd': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'headached': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'visiond': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'coughd': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'jointd': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'muscled': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'dyspnoead': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'wheezingd': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'eard': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'appetited': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'chestd': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'swallowingd': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'nausead': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'vomitd': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'diarrhead': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'abdominald': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'backd': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'hiccupsd': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'mouthd': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'throatd': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'nosed': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'rashd': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'seizured': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'bruisingd': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'confusiond': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'swellingd': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'neckd': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'urined': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'bloodd': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'stoolbloodd': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'nosebloodd': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'oralbloodd': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'vomitbloodd': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'vagbloodd': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'intravenousbloodd': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'othersymptomsd': {1: '< = 2 days', 2: '3-14 days', 3: '2+ weeks'},
    'ethnicityc_crf': {1: 'Bini', 2: 'Esan', 3: 'Etsako', 4: 'Hausa', 5: 'Igarra', 6: 'Igbo', 7: 'Owan', 8: 'Urhobo', 9: 'Yoruba', 10: 'Other'},
    'community_crf': {1: 'Rural', 2: 'Urban'},
    'state_crf': {1: "Abia", 2: "Adamawa", 3: "Akwa Ibom", 4: "Anambra", 5: "Bauchi", 6: "Bayelsa", 7: "Benue", 8: "Borno", 9: "Cross River", 10: "Delta", 11: "Ebonyi", 12: "Edo", 13: "Ekiti", 14: "Enugu", 15: "FCT", 16: "Gombe", 17: "Imo", 18: "Jigawa", 19: "Kaduna", 20: "Kano", 21: "Katsina", 22: "Kebbi", 23: "Kogi", 24: "Kwara", 25: "Lagos", 26: "Nasarawa", 27: "Niger", 28: "Ogun", 29: "Ondo", 30: "Osun", 31: "Oyo", 32: "Plateau", 33: "Rivers", 34: "Sokoto", 35: "Taraba", 36: "Yobe", 37: "Zamfara", 38: "Other (including other country)"},
    'comorbidity': {1: "Diabetes", 2: "Hypertension", 3: "Chronic cardiac disease", 4: "Chronic pulmonary disease", 5: "Cirrhosis", 6: "Liver diseases", 7: "Stroke", 8: "Solid tumor", 9: "Leukemia or lymphoma", 10: "HIV/AIDS", 11: "Sickle cell anemia", 12: "Rheumatologic disease", 13: "Dementia", 14: "Asplenia", 15: "Tuberculosis", 16: "Hepatitis B infection", 17: "Other", 18: "None/Not applicable"},
    'pregnancy_crf': {1: 'Yes', 0: 'No', 2: 'N/A'},
    'polygamy': {1: 'Yes', 0: 'No', 2: 'N/A'},
    'marital': {1: "Single, never married", 2: "Married or living as a couple", 3: "Divorced/separated"},
    'family_crf': {1: '<=4', 2: '>4'},
    'income_crf': {1: '<= 30,000 naira', 2: '>30,000 naira', 3: 'Not applicable', 4: 'Unknown'},
    'education_crf': {1: 'Informal', 2: 'Primary', 3: 'Secondary', 4: 'Post-secondary diploma', 5: 'Bachelor', 6: 'Higher than bachelor', 7: 'Vocational', 8: 'Not applicable'},
    'occupation2_crf': {1: 'Healthcare worker (government/private)', 2: 'Traditional healer', 3: 'Farmer', 4: 'Business person', 5: 'Livestock trader/butcher', 6: 'Other', 7: 'Not applicable', 8: 'Hunter/trader of game meat', 9: 'Miner/logger', 10: 'Religious leader', 11: 'Housewife', 12: 'Civil servant/government worker', 13: 'Transporter', 14: 'Teacher', 15: 'Student'},
    'occupation1_crf': {1: 'Government/Private employed', 2: 'Self-employed', 3: 'Unemployed', 4: 'Not Applicable'},
    'casecontrol': {1: 'Patient', 2: 'Control'}
}












